START TRANSACTION;

UPDATE provinces
SET area = CASE
    WHEN UPPER(TRIM(name)) IN (
        'QUANG NINH','HAI PHONG','HA NOI','LAO CAI','THAI NGUYEN','LANG SON','BAC NINH','PHU THO','HUNG YEN','NINH BINH'
    ) THEN 'NORTHERN'
    WHEN UPPER(TRIM(name)) IN (
        'THANH HOA','NGHE AN','HA TINH','QUANG TRI','HUE','DA NANG','QUANG NGAI','GIA LAI','KHANH HOA'
    ) THEN 'MIDDLE'
    WHEN UPPER(TRIM(name)) IN (
        'TP HO CHI MINH','DONG NAI','CAN THO','CA MAU','TAY NINH','DONG THAP','VINH LONG','AN GIANG'
    ) THEN 'SOUTHERN'
    ELSE area
END,
updated_at = NOW()
WHERE UPPER(TRIM(name)) IN (
    'QUANG NINH','HAI PHONG','HA NOI','LAO CAI','THAI NGUYEN','LANG SON','BAC NINH','PHU THO','HUNG YEN','NINH BINH',
    'THANH HOA','NGHE AN','HA TINH','QUANG TRI','HUE','DA NANG','QUANG NGAI','GIA LAI','KHANH HOA',
    'TP HO CHI MINH','DONG NAI','CAN THO','CA MAU','TAY NINH','DONG THAP','VINH LONG','AN GIANG'
);

COMMIT;
