-- Complete province list from vn.json sorted alphabetically
-- Using sequential ID from vn.json (id field, not properties.id)

DROP TABLE IF EXISTS ports;
DROP TABLE IF EXISTS provinces;

CREATE TABLE provinces (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_name (name),
    INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ports (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    province_id BIGINT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_province (province_id),
    INDEX idx_is_active (is_active),
    UNIQUE KEY uk_name_province (name, province_id),
    FOREIGN KEY (province_id) REFERENCES provinces(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert all 63 provinces sorted by name (alphabetically)
INSERT INTO provinces (id, name) VALUES
(9, 'An Giang'),
(55, 'Bà Rịa - Vũng Tàu'),
(32, 'Bạc Liêu'),
(57, 'Bắc Giang'),
(56, 'Bắc Ninh'),
(36, 'Bến Tre'),
(41, 'Bình Định'),
(61, 'Bình Dương'),
(5, 'Bình Phước'),
(38, 'Bình Thuận'),
(31, 'Cà Mau'),
(63, 'Cần Thơ'),
(21, 'Cao Bằng'),
(43, 'Đà Nẵng'),
(3, 'Đắk Lắk'),
(2, 'Đắk Nông'),
(11, 'Điện Biên'),
(54, 'Đông Bắc'),
(55, 'Đồng Bằng Sông Hồng'),
(37, 'Đông Nam Bộ'),
(8, 'Ðong Tháp'),
(4, 'Gia Lai'),
(20, 'Hà Giang'),
(60, 'Hà Nam'),
(53, 'Hà Nội'),
(15, 'Hà Tĩnh'),
(59, 'Hải Dương'),
(47, 'Hải Phòng'),
(33, 'Hậu Giang'),
(48, 'Hòa Bình'),
(29, 'Hồ Chí Minh city'),
(30, 'Khánh Hòa'),
(10, 'Kiên Giang'),
(1, 'Kon Tum'),
(23, 'Lai Châu'),
(62, 'Lâm Đồng'),
(24, 'Lạng Sơn'),
(22, 'Lào Cai'),
(7, 'Long An'),
(45, 'Nam Định'),
(14, 'Nghệ An'),
(44, 'Ninh Bình'),
(39, 'Ninh Thuận'),
(52, 'Phú Thọ'),
(40, 'Phú Yên'),
(19, 'Quảng Bình'),
(19, 'Quảng Nam'),
(42, 'Quảng Ngãi'),
(25, 'Quảng Ninh'),
(17, 'Quảng Trị'),
(26, 'Sóc Trăng'),
(12, 'Sơn La'),
(6, 'Tây Ninh'),
(13, 'Thanh Hóa'),
(46, 'Thái Bình'),
(58, 'Thái Nguyên'),
(18, 'Thừa Thiên - Huế'),
(27, 'Tiền Giang'),
(35, 'Trà Vinh'),
(49, 'Tuyên Quang'),
(51, 'Vĩnh Phúc'),
(34, 'Vĩnh Long'),
(50, 'Yên Bái');

-- Insert sample ports for provinces with known ports
INSERT INTO ports (name, province_id) VALUES
('Cái Lân (Cai Lan Port)', 25),
('Nghi Sơn Port', 13),
('Cửa Lò Port', 14),
('Vũng Áng Port', 15),
('Chân Mây Port', 18),
('Chu Lai Port', 19),
('Dung Quất Port', 42),
('Quy Nhơn Port', 41),
('Phú Mỹ (Phu My Port)', 28),
('ODA Thị Vải', 28),
('SP-PSA', 28),
('SP-ITC', 29),
('Nhà Bè Port', 29);
