/**
 * Pre-calculated province coordinates for map markers
 * Generated by scripts/generateProvinceCoordinates.ts
 * DO NOT EDIT MANUALLY - Run the script to regenerate
 */

export const PROVINCE_COORDINATES: Record<string, [number, number]> = {
  "An Giang": [
    105.57572,
    10.446396
  ],
  "Bac Ninh": [
    107.03352,
    21.319625
  ],
  "Ca Mau": [
    105.860463,
    9.364276
  ],
  "Can Tho": [
    106.298168,
    9.58847
  ],
  "Cao Bang": [
    106.8373,
    22.80287
  ],
  "Da Nang": [
    108.739287,
    15.398639
  ],
  "Dak Lak": [
    109.458875,
    12.881408
  ],
  "Dien Bien": [
    103.598477,
    21.682996
  ],
  "Dong Nai": [
    108.08,
    11.0
  ],
  "Dong Thap": [
    106.807813,
    10.395847
  ],
  "Gia Lai": [
    109.299418,
    13.829998
  ],
  "Ha Noi": [
    106.020128,
    21.041475
  ],
  "Ha Tinh": [
    106.510723,
    17.959937
  ],
  "Hai Phong": [
    106.909849,
    20.796868
  ],
  "Hue": [
    108.19492855700008,
    16.209770062000075
  ],
  "Hung Yen": [
    106.659473,
    20.607421
  ],
  "Khanh Hoa": [
    109.461776,
    12.6484
  ],
  "Lai Chau": [
    103.985094,
    21.96695
  ],
  "Lam Dong": [
    108.876634,
    11.354382
  ],
  "Lang Son": [
    107.363944,
    21.640057
  ],
  "Lao Cai": [
    105.100413,
    21.811453
  ],
  "Nghe An": [
    105.805989,
    19.274381
  ],
  "Ninh Binh": [
    106.585939,
    20.231941
  ],
  "Phu Tho": [
    105.858077,
    20.426202
  ],
  "Quang Ngai": [
    109.083977,
    14.672209
  ],
  "Quang Ninh": [
    108.088991,
    21.48497
  ],
  "Quang Tri": [
    107.389464,
    16.742918
  ],
  "Son La": [
    105.032913,
    20.773673
  ],
  "Tay Ninh": [
    106.748357,
    10.525201
  ],
  "Thai Nguyen": [
    106.247189,
    22.255977
  ],
  "Thanh Hoa": [
    106.07595,
    20.062722
  ],
  "TP Ho Chi Minh": [
    107.260964,
    10.4751
  ],
  "Tuyen Quang": [
    105.599155,
    22.522308
  ],
  "Vinh Long": [
    106.791831,
    10.113434
  ]
}

const COORDINATE_ALIASES: Record<string, string> = {
  'ho chi minh': 'tp ho chi minh',
}

function normalizeProvinceKey(value: string): string {
  return value
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

const PROVINCE_COORDINATES_NORMALIZED = Object.entries(PROVINCE_COORDINATES).reduce<Record<string, [number, number]>>(
  (acc, [name, coordinates]) => {
    acc[normalizeProvinceKey(name)] = coordinates
    return acc
  },
  {}
)

/**
 * Get coordinates for a province by name
 * Returns [0, 0] if province not found
 */
export function getProvinceCoordinates(provinceName: string): [number, number] {
  if (!provinceName) {
    return [0, 0]
  }

  const exactCoordinates = PROVINCE_COORDINATES[provinceName]
  if (exactCoordinates) {
    return exactCoordinates
  }

  const normalizedInput = normalizeProvinceKey(provinceName)
  const aliasKey = COORDINATE_ALIASES[normalizedInput] || normalizedInput

  return PROVINCE_COORDINATES_NORMALIZED[aliasKey] || [0, 0]
}

/**
 * Check if a province has coordinates
 */
export function hasProvinceCoordinates(provinceName: string): boolean {
  return provinceName in PROVINCE_COORDINATES
}

/**
 * Get all available province names
 */
export function getAvailableProvinces(): string[] {
  return Object.keys(PROVINCE_COORDINATES).sort()
}
