/**
 * Pre-calculated province coordinates for map markers
 * Generated by scripts/generateProvinceCoordinates.ts
 * DO NOT EDIT MANUALLY - Run the script to regenerate
 */

export const PROVINCE_COORDINATES: Record<string, [number, number]> = {
  "An Giang": [
    105.57572,
    10.446396
  ],
  "Bắc Ninh": [
    107.03352,
    21.319625
  ],
  "Cà Mau": [
    105.860463,
    9.364276
  ],
  "Cần Thơ": [
    106.298168,
    9.58847
  ],
  "Cao Bằng": [
    106.8373,
    22.80287
  ],
  "Đà Nẵng": [
    108.739287,
    15.398639
  ],
  "Đắk Lắk": [
    109.458875,
    12.881408
  ],
  "Điện Biên": [
    103.598477,
    21.682996
  ],
  "Đồng Nai": [
    107.577774,
    10.833085
  ],
  "Đồng Tháp": [
    106.807813,
    10.395847
  ],
  "Gia Lai": [
    109.299418,
    13.829998
  ],
  "Hà Nội": [
    106.020128,
    21.041475
  ],
  "Hà Tĩnh": [
    106.510723,
    17.959937
  ],
  "Hải Phòng": [
    106.909849,
    20.796868
  ],
  "Huế": [
    108.19492855700008,
    16.209770062000075
  ],
  "Hưng Yên": [
    106.659473,
    20.607421
  ],
  "Khánh Hòa": [
    109.461776,
    12.6484
  ],
  "Lai Châu": [
    103.985094,
    21.96695
  ],
  "Lâm Đồng": [
    108.876634,
    11.354382
  ],
  "Lạng Sơn": [
    107.363944,
    21.640057
  ],
  "Lào Cai": [
    105.100413,
    21.811453
  ],
  "Nghệ An": [
    105.805989,
    19.274381
  ],
  "Ninh Bình": [
    106.585939,
    20.231941
  ],
  "Phú Thọ": [
    105.858077,
    20.426202
  ],
  "Quảng Ngãi": [
    109.083977,
    14.672209
  ],
  "Quảng Ninh": [
    108.088991,
    21.48497
  ],
  "Quảng Trị": [
    107.389464,
    16.742918
  ],
  "Sơn La": [
    105.032913,
    20.773673
  ],
  "Tây Ninh": [
    106.748357,
    10.525201
  ],
  "Thái Nguyên": [
    106.247189,
    22.255977
  ],
  "Thanh Hóa": [
    106.07595,
    20.062722
  ],
  "TP. Hồ Chí Minh": [
    107.571928,
    10.6002
  ],
  "Tuyên Quang": [
    105.599155,
    22.522308
  ],
  "Vĩnh Long": [
    106.791831,
    10.113434
  ]
}

/**
 * Get coordinates for a province by name
 * Returns [0, 0] if province not found
 */
export function getProvinceCoordinates(provinceName: string): [number, number] {
  return PROVINCE_COORDINATES[provinceName] || [0, 0]
}

/**
 * Check if a province has coordinates
 */
export function hasProvinceCoordinates(provinceName: string): boolean {
  return provinceName in PROVINCE_COORDINATES
}

/**
 * Get all available province names
 */
export function getAvailableProvinces(): string[] {
  return Object.keys(PROVINCE_COORDINATES).sort()
}
