import * as fs from 'fs'
import * as path from 'path'

// Import the GeoJSON data
const vnGeoPath = path.join(__dirname, '../src/assets/newvn.json')
const vnGeo = JSON.parse(fs.readFileSync(vnGeoPath, 'utf-8'))

// Import the centroid calculation function
function calculateCentroid(geometry: any): [number, number] {
    if (!geometry) return [0, 0];

    let coordinates = geometry.coordinates;
    let type = geometry.type;

    if (type === 'Polygon') {
        return getCoastalPoint(coordinates);
    } else if (type === 'MultiPolygon') {
        // Find the largest polygon (main landmass)
        let maxPoints = 0;
        let mainPolygon = coordinates[0];

        for (const poly of coordinates) {
            if (poly[0].length > maxPoints) {
                maxPoints = poly[0].length;
                mainPolygon = poly;
            }
        }
        return getCoastalPoint(mainPolygon);
    }

    return [0, 0];
}

function getCoastalPoint(coordinates: any[]): [number, number] {
    // coordinates[0] is the outer ring (coastline)
    const ring = coordinates[0];

    // For coastal provinces, we want a point on the eastern or southern edge
    // Find the point with maximum longitude (eastmost) or minimum latitude (southmost)
    // This approximates a coastal location for Vietnam's geography

    let eastmostPoint = ring[0];
    let maxLon = ring[0][0];

    for (let i = 1; i < ring.length; i++) {
        const lon = ring[i][0];
        if (lon > maxLon) {
            maxLon = lon;
            eastmostPoint = ring[i];
        }
    }

    return [eastmostPoint[0], eastmostPoint[1]];
}

// Generate coordinates mapping
const provinceCoordinates: Record<string, [number, number]> = {}

if (vnGeo.features) {
    vnGeo.features.forEach((feature: any) => {
        const provinceName = feature.properties?.ten_tinh
        if (provinceName && feature.geometry) {
            const coords = calculateCentroid(feature.geometry)
            provinceCoordinates[provinceName] = coords
        }
    })
}

// Generate TypeScript file content
const outputContent = `/**
 * Pre-calculated province coordinates for map markers
 * Generated by scripts/generateProvinceCoordinates.ts
 * DO NOT EDIT MANUALLY - Run the script to regenerate
 */

export const PROVINCE_COORDINATES: Record<string, [number, number]> = ${JSON.stringify(provinceCoordinates, null, 2)}

/**
 * Get coordinates for a province by name
 * Returns [0, 0] if province not found
 */
export function getProvinceCoordinates(provinceName: string): [number, number] {
  return PROVINCE_COORDINATES[provinceName] || [0, 0]
}

/**
 * Check if a province has coordinates
 */
export function hasProvinceCoordinates(provinceName: string): boolean {
  return provinceName in PROVINCE_COORDINATES
}

/**
 * Get all available province names
 */
export function getAvailableProvinces(): string[] {
  return Object.keys(PROVINCE_COORDINATES).sort()
}
`

// Write to output file
const outputPath = path.join(__dirname, '../src/utils/provinceCoordinates.ts')
fs.writeFileSync(outputPath, outputContent, 'utf-8')

console.log(`✅ Generated province coordinates for ${Object.keys(provinceCoordinates).length} provinces`)
console.log(`📁 Output: ${outputPath}`)
console.log('\nSample coordinates:')
Object.entries(provinceCoordinates).slice(0, 5).forEach(([name, coords]) => {
    console.log(`  ${name}: [${coords[0].toFixed(4)}, ${coords[1].toFixed(4)}]`)
})
